### ISSUE TITLE
create() with children attribute error

### ISSUE THREAD

**Issue by murilozilli** [lazychaser/laravel-nestedset#192]
I am sending the following array to the create()
```
array(4) {
  ["name"]=>
  string(2) "cat1"
  ["company_id"]=>
  int(1)
  ["children"]=>
  array(3) {
    ["name"]=>
    string(5) "cat2"
    ["company_id"]=>
    int(1)
  }
}
```

Those categories don't exist in my DB.

It is creating only the first one `cat1` without setting `_lft` and `_rgt`(both null in DB) attributes then it is throwing an Exception

`Argument 1 passed to App\Model\Category::create() must be of the type array, string given, called in /vendor/kalnoy/nestedset/src/NodeTrait.php on line 776`

**Comment by murilozilli** [comment]
I managed to see I was not sending an array of arrays in the children attribute. Sorry about that. Anyway I think we could send also an array of arrays in the first dimension of the array, thus be able to create several root nodes in one create.

**Comment by murilozilli** [comment]
Actually fixing the `children` structure just gave me another exception.

Since the `_lft` and `_rgt` are being set with null I get the following errors:
`Node must exists.` at `/vendor/kalnoy/nestedset/src/NodeTrait.php:1155`

```
#0 /vendor/kalnoy/nestedset/src/NodeTrait.php(435): App\Model\Category->assertNodeExists(Object(App\Model\Category))
#1 /vendor/kalnoy/nestedset/src/NodeTrait.php(412): App\Model\Category->appendOrPrependTo(Object(App\Model\Category))
#2 /vendor/kalnoy/nestedset/src/NodeTrait.php(766): App\Model\Category->appendToNode(Object(App\Model\Category))
#3 /vendor/kalnoy/nestedset/src/NodeTrait.php(775): App\Model\Category::create(Array, Object(App\Model\Category))
#4 App\Model\Category::create(Array)

```

**Comment by lazychaser** [comment]
If you're using only Eloquent, you need it to generate events properly and for this, dispatcher should be set up

**Comment by murilozilli** [comment]
I have the events lib like I mentioned in the end on the copy of part of my composer.json.

**Comment by lazychaser** [comment]
Yes, but you need to set dispatcher on Eloquent

**Comment by murilozilli** [comment]
Well, I have this slice of code here:
```
$capsule = new Illuminate\Database\Capsule\Manager();
$capsule->addConnection($container['eloquent']);
$capsule->setAsGlobal();
$capsule->bootEloquent();
```

on `bootEloquent()` there is this:
```
if ($dispatcher = $this->getEventDispatcher()) {
    Eloquent::setEventDispatcher($dispatcher);
}
```

**Comment by ozanmuyes** [comment]
I had a similar problem; I'm seeding a table (Category) with complex nested data using Phinx. In the seeder file (CategoriesSeeder.php - which extends AbstractSeeder) I have an `init` method. In this very method I initialize a new Capsule (`use Illuminate\Database\Capsule\Manager as Capsule;`, add it to a new connection, set as global... as @murilozilli did in [there](https://github.com/lazychaser/laravel-nestedset/issues/192#issuecomment-293028672). And then in the `run` method I **set the model's event dispatcher** like so;
```php
Category::setEventDispatcher($this->capsule->getEventDispatcher());
```
Bam, events on the observer (CategoryObserver) working now. Hope this helps.

EDIT:
Right after the line that sets the model's event dispatcher that line exists (_the data below demonstration only_) and works as expected;
```php
Category::rebuildTree([
    [
        'name' => 'Category 1',
        // other fields of Category instance for "Category 1" (if any)

        'children' => [
            'name' => 'Subcategory 1 of Category 1'
            // other fields of Category instance for "Subcategory 1 of Category 1" (if any)

            // children of "Subcategory 1 of Category 1" (if any)
       ]
    ],
    [
        'name' => 'Category 2',
        // other fields of Category instance for "Category 2" (if any)

        // children of "Category 2" (if any)
    ],
    //
]);
```

**Comment by pixxelfactory** [comment]
Hi,

i have the same issue, tried the solution above to get an eventdispatcher instance, but:
$capsule->getEventDispatcher() returns NULL.

I use eloquent outside laravel and initialize it exactly the way murilozilli does.
Just the nestedset-trait does not work, it prints the same error as stated above =/

**Comment by drjoju** [comment]
I know this is an old question but here is my solution. I'm working with eloquent outside laravel and initialize capsule in this way.


```
// Create new IoC Container instance
$container = new Container;
$container->bind('app', $container);

//  Capsule
$capsule = new Capsule;

$capsule->addConnection([
    'driver' =>'mysql',
    'host' => $dbhost,
    'database' => $dbname,
    'username' => $dbuname,
    'password' => $dbpass,
    'charset' => 'utf8',
    'collation' => 'utf8_unicode_ci',
    'prefix' => $prefix."_",
]);

$capsule->setEventDispatcher(new Dispatcher);

// Make this Capsule instance available globally via static methods... (optional)
$capsule->setAsGlobal();

// Eloquent
$capsule->bootEloquent();

$container->instance("capsule", $capsule);

```
Without this line, 

**$capsule->setEventDispatcher(new Dispatcher);**

the code does not work.




Best regards
